version: "3.9"

services:
  api:
    build: .
    container_name: sikokar-be-api
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mariadb:10.4
    container_name: sikokar-be-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_sikokar
      MYSQL_USER: sikokar
      MYSQL_PASSWORD: sikokar
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:
